#!/bin/bash
# PreToolUse guard: refuse direct edits to the generated HTML.
#
# Every *.html at the repo root is emitted by scripts/build.py. Editing one
# directly appears to work and is then silently overwritten by the next build,
# so the work is lost with no error. This denies the edit and points at the
# real source.
#
# Self-locating: only guards a .html file whose own directory contains
# scripts/build.py, so it stays correct if the repo moves and never fires on
# unrelated HTML elsewhere on disk.

payload=$(cat)
f=$(printf '%s' "$payload" | jq -r '.tool_input.file_path // empty' 2>/dev/null)

[ -z "$f" ] && exit 0
case "$f" in *.html) ;; *) exit 0 ;; esac

dir=$(cd "$(dirname "$f")" 2>/dev/null && pwd) || exit 0
[ -f "$dir/scripts/build.py" ] || exit 0

name=$(basename "$f")
jq -n --arg n "$name" '{
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    permissionDecision: "deny",
    permissionDecisionReason: ($n + " is generated by scripts/build.py and any direct edit is overwritten by the next build. Edit the page content in scripts/build.py, then run: /usr/bin/python3 scripts/build.py")
  }
}'
